# Generated by Django 4.0.4 on 2022-06-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book', max_length=100)),
                ('authors', models.CharField(help_text='Authors of the book', max_length=200)),
                ('acquired', models.BooleanField(default=False, verbose_name='Status of the book: acquired?')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Publication date of the book.')),
                ('thumbnail', models.URLField(blank=True, verbose_name='URL to thumbnail of the book')),
            ],
        ),
    ]
